TUTORIAL_PAGE1_TITLE = 'Для чего MidHub?'
TUTORIAL_PAGE1_SUBTITLE = 'MidHub это ваш аккаунт на основе биометрии. Один для всех сервисов. Пароль к нему невозможно забыть или украсть, а главное – он всегда с вами.'
TUTORIAL_PAGE2_TITLE = 'Аккаунт MidHub — это лиценция'
TUTORIAL_PAGE2_SUBTITLE = 'Они бывают трех типов. Белая верификация – это базовая возможность авторизоваться с помощью биометрии. Желтая – подтверждение личности с помощью паспорта. Зеленая - полная верификация аккаунта через нотариуса.'
TUTORIAL_PAGE3_TITLE = 'Получение верификации'
TUTORIAL_PAGE3_SUBTITLE = 'Белую верификацию можно получить за пару минут. Выдача желтой верификации займет не больше часа – нотариус проверит ваши документы. Для получения зеленой верификации нужно встретиться с нотариусом лично, вы получите верификацию в тот же день.'
LOGIN_BUTTON = 'ВОЙТИ'
CREATE_ACC_BUTTON = 'СОЗДАТЬ\nАККАУНТ'
LOGO = 'MidHub'
SUBTITLE_LOGIN = 'Если у вас уже есть аккаунт'
WALLET_INFO_ADDRESS = 'Адрес: '
WALLET_INFO_BALANCE = 'Баланс: '
WALLET_INFO_NEXT    = 'ПРОДОЛЖИТЬ'
RESTART_APP_TOAST = 'Application restart required!'
COPIED_WALLET_ADDRESS_TOAST = 'Адрес скопирован в буфер обмена.'
BUNDLE_ID = 'ru.mobileup.midhub'

# Docs tab
CHECKING_DOCS         = 'Проверяются'
READY_DOCS            = 'Выданные'
MY_DOCS_HEADER        = 'Мои документы'
ADD_DOC_BUTTON        = 'ДОБАВИТЬ ДОКУМЕНТ'
EMPTY_READY_TAB       = 'У Вас еще нет ни одного документа.\n\nНажмите "Добавить документ" и верифицируйте Ваш паспорт или другое удостоверение личности.'
EMPTY_CHECKING_TAB    = 'У Вас еще нет ни одной заявки.\n\nНажмите "Добавить документ" и верифицируйте Ваш паспорт или другое удостоверение личности.'
CHOOSE_COUNTRY_HEADER = 'Выберите страну'
ENTER_NAME            = 'Введите название'
FIRST_STEP            = 'ШАГ 1 ИЗ 4'
SECOND_STEP           = 'ШАГ 2 ИЗ 4'
THIRD_STEP            = 'ШАГ 3 ИЗ 4'
FOURTH_STEP           = 'ШАГ 4 ИЗ 4'
COUNTRY_GROUP_TITLE   = 'Все страны'
CHOOSE_DOC            = 'Выберите документ'
SUBHEADER             = 'Документы'
CHANGE_DOMAIN_BUTTON  = 'ИЗМЕНИТЬ'
ADD_DOC_FORM_HEADER   = 'Заполните форму'
STEP_NAME_PASSPORT    = 'Паспорт гражданина РФ'
NEXT_BUTTON           = 'ДАЛЕЕ'
ATTACH_DOC_BUTTON     = 'ДОБАВИТЬ ФОТО'
AGREEMENT_LABEL       = 'Соглашаюсь с условиями сервиса и обработкой персональных данных'
REQUEST_MESSAGE       = 'Ваша заявка отправлена в обработку. Идет поиск нотариуса'
NOTIFICATION_MESSAGE  = 'Это может занять от нескольких минут до часа. Вы можете закрыть приложение. Мы оповестим вас с помощью push-уведомления.'
PENDING_STATUS        = 'Ожидает нотариуса'
MINING_STATUS         = 'Ожидает майнинга'

# Types of verification
GLOBAL_VERIFICATION_TITLE   = 'МЕЖДУНАРОДНАЯ ВЕРИФИКАЦИЯ'
LOCAL_VERIFICATION_TITLE    = 'ЛОКАЛЬНАЯ ВЕРИФИКАЦИЯ'
YELLOW_TITLE                = 'Желтый тип'
GREEN_TITLE                 = 'Зеленый тип'
GLOBAL_YELLOW_DESC          = 'Дистанционная верификация по международным стандартам'
GLOBAL_GREEN_DESC           = 'Личная верификация по международным стандартам'
LOCAL_YELLOW_DESC           = 'Дистанционная верификация в соответствии с местными требованиями законодательства'
LOCAL_GREEN_DESC            = 'Личная верификация в соответствии с местными требованиями законодательства'
VERIFICATION_CHOOSE_BUTTON  = 'ВЫБРАТЬ'
VERIFICATION_DETAILS_BUTTON = 'ПОДРОБНЕЕ'
ALERT_NOT_SUPPORTED_VERIF   = 'Выбранный тип верификации временно не поддерживается'
ALERT_OK_BUTTON             = 'OК'

# Yellow verification details
YELLOW_MAIN_TITLE   = 'Желтая международная верификация'
YELLOW_SUBTITLE     = 'Персонифицированный аккаунт'
YELLOW_DESC         = 'Желтая верификация позволяет привязать ваши паспортные данные к биометрии и подтвердить личность документально.'
YELLOW_POINT_ONE    = 'Личные данные подтверждены нотариусом по вашим документам'
YELLOW_POINT_TWO    = 'Лицензия принимается большинством сервисов, за исключением финансовых'
YELLOW_POINT_THREE  = 'Только вы решаете, какую именно информацию предоставить конкретному сервису'
YELLOW_POINT_FOUR   = 'Безопасность ваших данных гарантирована системой блокчейн'
